---
name: Lint
on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/common
      - run: uv run ruff format --check ./src tests/
      - run: uv run ruff check ./src tests/
      - run: uv run ty check src tests
      - run: uv lock --check
