---
name: Lint
on:
  push:
    branches-ignore:
      - "main"
      - "master"
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/common
      - run: pdm lint
