---
name: Build Python package
on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common
      - name: Build the Python dist
        run: pdm build
      - name: Export the Python dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
