# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
        # Always check, not only during merges
        args: [--assume-in-merge]
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.14.0
    hooks:
      - id: hadolint
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.8
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.14
    hooks:
      - id: ruff-format
      - id: ruff
