---
name: "Common"
description: "Common steps for all Actions"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - uses: astral-sh/setup-uv@v6
    - run: uv sync
      shell: bash
